#!/bin/bash

alias ls='ls --color=auto --group-directories-first'
alias la='ls -lAh --group-directories-first'
alias ll='ls -lh --group-directories-first'
alias lh='ls -ld --group-directories-first .?*'
alias rm='rm -i'
alias vim='nvim'
alias img='sxiv -f'
alias grep='grep --color=auto'
alias yt='yt-dlp --config-location=~/.config/youtube-dl/config'
alias ds='du -sh ./* | sort -h; du -sh'
alias myip='curl https://ipinfo.io/ip;echo'
alias ez='nvim ~/.config/zsh/.zshrc'
alias ep='nvim ~/.zprofile'
alias et='nvim ~/.tmux.conf'

# create and cd into directory
cnc(){
  mkdir -p "$1"
  cd "$1" || return
}
