#!/bin/sh

# Autostart
sxhkd &
nm-applet &
nitrogen --restore &
xrdb ~/.Xresources &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width            2
bspc config window_gap              5

bspc config focus_follows_pointer   true
bspc config top_padding             24

bspc config normal_border_color	    "#282A36"
bspc config focused_border_color    "#BD93F9"
bspc config urgent_border_color     "#EC5F67"

# Rules
bspc rule -a Zathura state=tiled

$HOME/.config/polybar/launch.sh
