#!/bin/bash

# Global settings
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier control
bspc config click_to_focus none
bspc config focus_follows_pointer true

bspc config normal_border_color	"4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

#Desktop settings
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

$HOME/.config/polybar/launch.sh
