#!/bin/sh

# Autostart
sxhkd &
nm-applet &
dunst &
nitrogen --restore &

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Other
bspc config border_width            3
bspc config window_gap              5

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config top_padding             24
bspc config bottom_padding          0
bspc config left_padding            0
bspc config right_padding           0

bspc config focus_follows_pointer   true
bspc config pointer_modifier        control
bspc config pointer_action1         resize_corner

bspc config normal_border_color	    "#282A36"
bspc config focused_border_color    "#BD93F9"
bspc config urgent_border_color     "#EC5F67"

# Rules
bspc rule -a Zathura state=tiled
bspc rule -a mpv state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on

# Polybar
$HOME/.config/polybar/launch.sh
