[project]
name = "dotfiles"
version = "0.0.1"
requires-python = "~=3.13"
dependencies = ["ansible"]

[dependency-groups]
dev = []

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
